development:
  spotify_client_id: 'your_client_id'
  spotify_client_secret: 'your_client_secret'
  spotify_callback: 'your_callback'
  lastfm_api_id: 'your_api_id'
  lastfm_api_secret: 'your_api_secret'

test:
  spotify_client_id: 'your_client_id'
  spotify_client_secret: 'your_client_secret'
  spotify_callback: 'your_callback'
  lastfm_api_id: 'your_api_id'
  lastfm_api_secret: 'your_api_secret'

# set ENV variables in production