development:
  spotify_client_id: 'your_client_id'
  spotify_client_secret: 'your_client_secret'
  spotify_callback: 'your_callback'

test:
  spotify_client_id: 'your_client_id'
  spotify_client_secret: 'your_client_secret'
  spotify_callback: 'your_callback'

# set ENV variables in production